name: Clean-Images

on:
  push:
    paths:
      - 'src/*.pdf'
  workflow_dispatch:

jobs:
  move_pdfs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fix ImageMagick Policy
      run: |
        sudo apt install poppler-utils
    - name: Move PDF files
      run: |

        # Navigate to the folder containing the pdfs
        cd src/
        #converts all .pdf images into .png images:
        for f in *.pdf; do
            pdftoppm -png -r 300 "$f" "${f%.pdf}"
            #Removes the "-1" from the end of the file names filename-1.png
            mv "${f%.pdf}-1.png" "${f%.pdf}.png"
        done
        # Find all pdf files in the folder and move them to a different folder
        find . -name '*.png' -exec mv {} ../images/ \;
        find . -name '*.pdf' -exec mv {} ../images/ \;
        # Remove all the auxillary files with extensions .aux, .fls, .lof, .log, .out, .synctex.gz:
        find . -name '*.aux' -exec rm {} \;
        find . -name '*.fls' -exec rm {} \;
        find . -name '*.lof' -exec rm {} \;
        find . -name '*.log' -exec rm {} \;
        find . -name '*.out' -exec rm {} \;
        # find . -name '*.dvi' -exec rm {} \;
        # fing . -name '*.fdb_latexmk' -exec rm {} \;
        find . -name '*.synctex.gz' -exec rm {} \;

    - name: Add changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A

    - name: Commit changes
      run: git commit -m "Move PDF files to images folder"

    - name: Push changes
      run: git push origin main
